version:  "3"

services:
    back:
        container_name: currency_back
        build: ./back
        ports:
            - "8181:8080"
    front:
        depends_on:
            - back
        container_name: currency_front
        build: ./front/
        ports:
            - "3000:3000"