version:  "3"

services:
    back:
        container_name: finance_back_end
        build: .
        networks:
            - app-network
        volumes:
            - finance_public:/public/build/

    reverse_proxy:
        depends_on:
            - back
        container_name: finance_nginx
        image: nginx:mainline-alpine
        volumes:
            - finance_public:/var/www/html
            - ./nginx/:/etc/nginx/conf.d
        ports:
            - "80:80"
        networks:
            - app-network

networks:
    app-network:
      driver: bridge

volumes:
    finance_public: