version:  "3"

services:
    back_end:
        container_name: currency_back
        build: ./back
        ports:
            - "5000:5000"

    front_end:
        depends_on:
            - back_end
        container_name: currency_front
        build: ./front
        ports:
            - "3000:3000"
        stdin_open: true